[package]
name = "neo4j-experiment"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
neo4rs = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["full"] }