version: "3.9"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped

    ports:
      - "7687:7687"
      - "7474:7474"

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

    environment:
      - NEO4J_AUTH=neo4j/password

volumes:
  neo4j_data:
  neo4j_logs: